### ISSUE TITLE
Old "what is sigstore?" url is 404, leads to menu links breaking

### ISSUE THREAD

**Issue by axelsimon** [sigstore/sigstore-website#60]
**Description**
https://www.sigstore.dev/what_is_sigstore/ used to be the URL for the explainer page. It has been referenced several times from other parts of the web. With the new site, it's been replaced by https://www.sigstore.dev/how-it-works
The old URL is now 404 and leads to a non-descript error page.
It should really redirect to the new URL.

Beyond that, once you've landed on https://www.sigstore.dev/what_is_sigstore/, most links in the top menu  appear to be relative and so lead to further non-existent pages, such as https://www.sigstore.dev/what_is_sigstore/how-it-works
Those links should probably be absolute.

**Comment by mdunbavan** [comment]
Hi @axelsimon I developed the site but I have since finished the contract.

What we need to do is setup 301 redirects in Netlify so these urls do not break and give a 404.

The best way to do this is in the root folder create a `_redirects` file.

Inside this file you add redirects like so:

`http://oldurl.com https://newurl.com 301!`

I hope this helps.

**Comment by lukehinds** [comment]
hi @mdunbavan is the old site archived somewhere, I can't find any of the original branches like gh-pages?

**Comment by haydentherapper** [comment]
Closing this, as it's been awhile now and I can't find references to that link on Google with a quick search
